[package]
name = "flashd"
version = "0.1.0"
authors = ["Jamey Sharp <jamey@minilop.net>"]
edition = "2018"
license = "GPL-3.0-only"

[dependencies]
base64 = "0.13.0"
blake2 = "0.9.1"
memchr = "2"
tokio = { version = "1", features = ["full"] }
futures = "0.3.12"
async-compat = "0.2.0"
